/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Apoio.Cliente;
import Apoio.Servidor;
import daos.AgendasDAO;
import daos.ServicosHasPrestadoresDAO;
import entidades.Agendas;
import entidades.Servicos;
import entidades.ServicosHasPrestadores;
import entidades.Usuarios;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adriano
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public static Servidor servidor;
    Cliente cliente;
    public static ArrayList<Integer> idsAgendamentos;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        /* inicia com tela maximizada */
        this.setExtendedState(MAXIMIZED_BOTH);
        Usuarios u = IfrLogin.userAtivo;
        tfdUsuarioLogado.setText("Bem Vindo " + u.getNome());
        idsAgendamentos = new ArrayList<>();
        lblIcon.setVisible(false);
        cliente = new Cliente("239.0.0.1", 60000, null, lblIcon);
        cliente.start();
        servidor = new Servidor("239.0.0.1", 60000, null);
        servidor.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdUsuarioLogado = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuPrestadores = new javax.swing.JMenuItem();
        jMenuServicos = new javax.swing.JMenuItem();
        jMenuUsuariosSistema = new javax.swing.JMenuItem();
        jMenuAgendamentos = new javax.swing.JMenu();
        jMenuIncluirReserva = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuUtilitarios = new javax.swing.JMenu();
        jMenuGerarBackup = new javax.swing.JMenuItem();
        jMenuStatusLogs = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ServicesHelp");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/servicos-gerais2.png"))); // NOI18N

        tfdUsuarioLogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfdUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/aalerta.jpg"))); // NOI18N
        lblIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconMouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfdUsuarioLogado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(tfdUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Clients.png"))); // NOI18N
        jButton1.setText("Clientes");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Prestador de serviço.png"))); // NOI18N
        jButton2.setText("Pres. Serviços");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Agendamento.png"))); // NOI18N
        jButton3.setText("Agendamentos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Desligar.png"))); // NOI18N
        jButton4.setText("Sair do Sistema");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(202, 202, 202))
        );

        jMenu1.setText("                                                          ");
        jMenuBar1.add(jMenu1);

        jMenuCadastros.setText("Cadastros");

        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Clients.png"))); // NOI18N
        jMenuClientes.setText("Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuClientes);

        jMenuPrestadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Prestador de serviço.png"))); // NOI18N
        jMenuPrestadores.setText("Prestadores Serviço");
        jMenuPrestadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrestadoresActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuPrestadores);

        jMenuServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Services.png"))); // NOI18N
        jMenuServicos.setText("Serviços");
        jMenuServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuServicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuServicos);

        jMenuUsuariosSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/adduser.png"))); // NOI18N
        jMenuUsuariosSistema.setText("Usuário do Sistema");
        jMenuUsuariosSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosSistemaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuUsuariosSistema);

        jMenuBar1.add(jMenuCadastros);

        jMenuAgendamentos.setText("Manutenção");

        jMenuIncluirReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Agendamento.png"))); // NOI18N
        jMenuIncluirReserva.setText("Agendamentos");
        jMenuIncluirReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIncluirReservaActionPerformed(evt);
            }
        });
        jMenuAgendamentos.add(jMenuIncluirReserva);

        jMenuBar1.add(jMenuAgendamentos);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuUtilitarios.setText(" Utilitários");

        jMenuGerarBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/backup-restore.png"))); // NOI18N
        jMenuGerarBackup.setText("Gerar Backup");
        jMenuGerarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerarBackupActionPerformed(evt);
            }
        });
        jMenuUtilitarios.add(jMenuGerarBackup);

        jMenuStatusLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/finder.png"))); // NOI18N
        jMenuStatusLogs.setText("Status Gravar Logs");
        jMenuStatusLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuStatusLogsActionPerformed(evt);
            }
        });
        jMenuUtilitarios.add(jMenuStatusLogs);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/finder.png"))); // NOI18N
        jMenuItem2.setText("Util CEP");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuUtilitarios.add(jMenuItem2);

        jMenuBar1.add(jMenuUtilitarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed
        IfrClientes IfrClientes = new IfrClientes();
        jDesktopPane1.add(IfrClientes);
        IfrClientes.setVisible(true);
    }//GEN-LAST:event_jMenuClientesActionPerformed

    private void jMenuPrestadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrestadoresActionPerformed
        IfrPrestadores IfrPrestadores = new IfrPrestadores();
        jDesktopPane1.add(IfrPrestadores);
        IfrPrestadores.setVisible(true);
    }//GEN-LAST:event_jMenuPrestadoresActionPerformed

    private void jMenuUsuariosSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosSistemaActionPerformed
        IfrUsuarios IfrUsuarios = new IfrUsuarios();
        jDesktopPane1.add(IfrUsuarios);
        IfrUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosSistemaActionPerformed

    private void jMenuIncluirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIncluirReservaActionPerformed
        IfrAgendamentos IfrAgendamentos = new IfrAgendamentos();
        jDesktopPane1.add(IfrAgendamentos);
        IfrAgendamentos.setVisible(true);
    }//GEN-LAST:event_jMenuIncluirReservaActionPerformed

    private void jMenuGerarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerarBackupActionPerformed
        fazerBackup();
    }

    private void fazerBackup() {
        try {
            ProcessBuilder pb;

            Process p;

            // ajustar o caminho do executavel de acordo com o SO
            // aqui foi considerado usuario: postgres banco: emprestimos
            // o caminho de destino pode ser solicitado ao usuário
            pb = new ProcessBuilder("C:/Program Files/PostgreSQL/9.5/bin/pg_dump.exe", "-h", "localhost", "-p", "5432", "-U", "postgres", "-F", "c", "-b", "-v", "-f", "C:/Users/asimon/Documents/NetBeansProjects/ServicesHelp/BKP/BKP_ServicesHelp.backup", "ServicesHelp");

            // informa-se a senha: postgres
            // sugestao: deixar gravado em um cadastro de parametros ou solicitar no momento do backup
            pb.environment().put("PGPASSWORD", "postgres");

            pb.redirectErrorStream(true);

            p = pb.start();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao executar backup: " + ex);
        }
    }//GEN-LAST:event_jMenuGerarBackupActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuServicosActionPerformed
        IfrServicos IfrServiços = new IfrServicos();
        jDesktopPane1.add(IfrServiços);
        IfrServiços.setVisible(true);
    }//GEN-LAST:event_jMenuServicosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IfrClientes IfrClientes = new IfrClientes();
        jDesktopPane1.add(IfrClientes);
        IfrClientes.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuStatusLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuStatusLogsActionPerformed
        DlgAtivaDesativaLogs dlgLogs = new DlgAtivaDesativaLogs(null, true, this);
        dlgLogs.setLocationRelativeTo(null);
        dlgLogs.setModal(true);
        dlgLogs.setVisible(true);
    }//GEN-LAST:event_jMenuStatusLogsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        IfrAgendamentos IfrAgendamentos = new IfrAgendamentos();
        jDesktopPane1.add(IfrAgendamentos);
        IfrAgendamentos.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        IfrPrestadores IfrPrestadores = new IfrPrestadores();
        jDesktopPane1.add(IfrPrestadores);
        IfrPrestadores.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        IfrUtilCep IfrUtilCep = new IfrUtilCep();
        jDesktopPane1.add(IfrUtilCep);
        IfrUtilCep.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void lblIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconMouseClicked
        String alerta = "Novo(s) serviço(s) agendado(s):";
        for (int i = 0; i < idsAgendamentos.size(); i++) {
            Agendas a = (Agendas) new AgendasDAO().consultarId(idsAgendamentos.get(i));
            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            String data = df.format(a.getInicioEstimado());
            String servico = a.getRefServicosHasPrestadores().getRefServicos().getDescricao();
            String cliente = a.getRefClientes().getNome();
            alerta += "\n " + data + ": " + servico + " para " + cliente;
        }
        lblIcon.setVisible(false);
        JOptionPane.showMessageDialog(this, alerta);
    }//GEN-LAST:event_lblIconMouseClicked

    
      
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAgendamentos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuGerarBackup;
    private javax.swing.JMenuItem jMenuIncluirReserva;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuPrestadores;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenuItem jMenuServicos;
    private javax.swing.JMenuItem jMenuStatusLogs;
    private javax.swing.JMenuItem jMenuUsuariosSistema;
    private javax.swing.JMenu jMenuUtilitarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel tfdUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
