/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Apoio.ConexaoBD;
import Apoio.Formatacao;
import static Apoio.Formatacao.removerFormatacao;
import Apoio.LimiteDigitos;
import Apoio.limpaCampos;
import daos.AgendasDAO;
import daos.ClientesDAO;
import daos.ServicosHasPrestadoresDAO;
import entidades.Agendas;
import entidades.Clientes;
import entidades.ServicosHasPrestadores;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adriano
 */
public class IfrAgendamentos extends javax.swing.JInternalFrame {

    AgendasDAO agendasDAO;
    int idCli = 0;
    int idSerPres = 0;

    /**
     * Creates new form IfrCategoria
     */
    public IfrAgendamentos() {
        initComponents();
        agendasDAO = new AgendasDAO();
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(false);
//        tfdIdCliente.setVisible(false);
//        tfdIdPS.setVisible(false);
        tfdDescricao.setDocument(new LimiteDigitos(250));
        tfdObsCliente.setDocument(new LimiteDigitos(250));
        tfdObsPrestador.setDocument(new LimiteDigitos(250));
        tfdHoraIni.setDocument(new LimiteDigitos(5));
        tfdHoraFim.setDocument(new LimiteDigitos(5));
        tfdTempo.setDocument(new LimiteDigitos(5));
        tfdNota.setDocument(new LimiteDigitos(2));

    }

    public Date formDataStrgToJava(String data) {
        /* Função de conversão de uma data do tipo STRING dd-MM-yyyy para formato
         * date do java.util
         */
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");//Formato da data que virá do banco
        Date date = null;
        try {
            date = (Date) formatter.parse(data);//convertendo o formato para Date
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcurar = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendas = new javax.swing.JTable();
        tfdConsultaDataSaidaDe = new org.jdesktop.swingx.JXDatePicker();
        tfdConsultaDataSaidaAte = new org.jdesktop.swingx.JXDatePicker();
        tfdConsultaDesc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfdConsultaCli = new javax.swing.JTextField();
        tfdConsultaPrest = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        tfdConsultaServ = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfdConsultaDataSaidaDe1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel24 = new javax.swing.JLabel();
        tfdConsultaDataSaidaAte1 = new org.jdesktop.swingx.JXDatePicker();
        btnLimpar1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        tfdConsultaServ1 = new javax.swing.JTextField();
        jPanelInclusao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JxDataIni = new org.jdesktop.swingx.JXDatePicker();
        tfdHoraIni = new javax.swing.JFormattedTextField();
        tfdDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfdCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        tfdPrestador = new javax.swing.JTextField();
        btnBuscarPrestServ = new javax.swing.JButton();
        tfdIdCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfdIdAgenda = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JxDataFim = new org.jdesktop.swingx.JXDatePicker();
        tfdHoraFim = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfdValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdObsCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfdObsPrestador = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfdNota = new javax.swing.JTextField();
        tfdServico = new javax.swing.JTextField();
        tfdIdPS = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        rdbProgramado = new javax.swing.JRadioButton();
        rdbRealizado = new javax.swing.JRadioButton();
        rdbSuspenso = new javax.swing.JRadioButton();
        tfdTempo = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btnProcurar.setText("Buscar");

        setTitle("Agendamentos");

        tblAgendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAgendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAgendasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgendas);

        jLabel14.setText("Descrição");

        jLabel15.setText("Cliente");

        jLabel16.setText("Prestador");

        jLabel17.setText("Período de início");

        jLabel19.setText("até");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel22.setText("Serviço");

        jLabel23.setText("Período fim");

        jLabel24.setText("até");

        btnLimpar1.setText("Filtrar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Nota");

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(38, 38, 38)
                                .addComponent(tfdConsultaServ))
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(38, 38, 38)
                                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdConsultaCli, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(tfdConsultaDesc)
                                    .addComponent(tfdConsultaPrest, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(55, 55, 55)
                                .addComponent(tfdConsultaDataSaidaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addGap(15, 15, 15)
                                .addComponent(tfdConsultaDataSaidaAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))
                                .addGap(55, 55, 55)
                                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                        .addComponent(tfdConsultaDataSaidaDe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24)
                                        .addGap(15, 15, 15)
                                        .addComponent(tfdConsultaDataSaidaAte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdConsultaServ1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfdConsultaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdConsultaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdConsultaPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdConsultaServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25))
                        .addGap(55, 55, 55))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdConsultaDataSaidaAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdConsultaDataSaidaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdConsultaDataSaidaAte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdConsultaDataSaidaDe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addComponent(tfdConsultaServ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpar)
                            .addComponent(btnLimpar1))
                        .addGap(14, 14, 14)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanelConsulta);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agendamentos");

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Dt Início");

        JxDataIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JxDataIniActionPerformed(evt);
            }
        });

        tfdHoraIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdHoraIni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdHoraIni.setText("  :  ");
        tfdHoraIni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdHoraIniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdHoraIniKeyTyped(evt);
            }
        });

        tfdDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdDescricaoKeyReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Descrição");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Cliente");

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Prestador/Serviço");

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Tempo Exec.");

        tfdCliente.setEditable(false);

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/fin2.png"))); // NOI18N
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        tfdPrestador.setEditable(false);

        btnBuscarPrestServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/fin2.png"))); // NOI18N
        btnBuscarPrestServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestServActionPerformed(evt);
            }
        });

        tfdIdCliente.setEditable(false);
        tfdIdCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("h");

        jLabel13.setText("Id");

        tfdIdAgenda.setEditable(false);
        tfdIdAgenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Campos em vermelho Obrigatórios");

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Dt Fim");

        tfdHoraFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdHoraFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdHoraFim.setText("  :  ");
        tfdHoraFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdHoraFimFocusGained(evt);
            }
        });
        tfdHoraFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdHoraFimKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdHoraFimKeyTyped(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("h");

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("h");

        tfdValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdValorKeyReleased(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Valor Trabalho");

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Obs. Cliente");

        tfdObsCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdObsClienteKeyReleased(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Obs. Prestador");

        tfdObsPrestador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdObsPrestadorKeyReleased(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("Nota");

        tfdNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdNotaKeyReleased(evt);
            }
        });

        tfdServico.setEditable(false);

        tfdIdPS.setEditable(false);
        tfdIdPS.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel26.setForeground(new java.awt.Color(255, 51, 51));
        jLabel26.setText("Situação");

        buttonGroup1.add(rdbProgramado);
        rdbProgramado.setText("Programado");

        buttonGroup1.add(rdbRealizado);
        rdbRealizado.setText("Realizado");

        buttonGroup1.add(rdbSuspenso);
        rdbSuspenso.setText("Suspenso");

        tfdTempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdTempoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelInclusaoLayout = new javax.swing.GroupLayout(jPanelInclusao);
        jPanelInclusao.setLayout(jPanelInclusaoLayout);
        jPanelInclusaoLayout.setHorizontalGroup(
            jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInclusaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInclusaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdNota, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                .addComponent(JxDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfdHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11))
                                            .addComponent(tfdPrestador, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addComponent(tfdCliente)
                                            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                .addComponent(tfdTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18)))
                                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInclusaoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                                                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(JxDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfdHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel12)))
                                                .addGap(124, 124, 124))
                                            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tfdIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(tfdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnBuscarPrestServ, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfdIdPS, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(tfdObsCliente)
                                    .addComponent(tfdObsPrestador, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                        .addComponent(tfdIdAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(256, 256, 256))
                                    .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                                        .addComponent(rdbProgramado)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbRealizado)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbSuspenso)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanelInclusaoLayout.setVerticalGroup(
            jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfdIdAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rdbProgramado)
                    .addComponent(rdbRealizado)
                    .addComponent(rdbSuspenso))
                .addGap(18, 18, 18)
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInclusaoLayout.createSequentialGroup()
                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JxDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(JxDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfdIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfdIdPS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfdPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(tfdServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBuscarPrestServ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel18)
                        .addComponent(tfdTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdObsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdObsPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel21))
        );

        jTabbedPane1.addTab("Inclusão de Agendamentos", jPanelInclusao);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/exit.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/delete2.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean camposObrigatorios() {
        if (tfdDescricao.getText().length() > 0 && removerFormatacao(tfdHoraIni.getText()).trim().length() > 0 && removerFormatacao(tfdHoraFim.getText()).trim().length() > 0 && tfdIdCliente.getText().length() > 0
                && tfdIdPS.getText().length() > 0) {
            return true;
        } else {
            return false;
        }
    }

    private void tblAgendasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendasMouseReleased
        btnExcluir.setEnabled(true);
        btnEditar.setEnabled(true);
    }//GEN-LAST:event_tblAgendasMouseReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCamposConsulta();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tfdObsClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdObsClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdObsClienteKeyReleased

    private void tfdHoraFimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdHoraFimKeyTyped
        String caracteres = "0987654321:";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfdHoraFimKeyTyped

    private void tfdHoraFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdHoraFimKeyReleased
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_tfdHoraFimKeyReleased

    private void tfdDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdDescricaoKeyReleased
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_tfdDescricaoKeyReleased

    private void tfdHoraIniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdHoraIniKeyTyped
        String caracteres = "0987654321:";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfdHoraIniKeyTyped

    private void tfdHoraIniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdHoraIniKeyReleased
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_tfdHoraIniKeyReleased


    private void tfdObsPrestadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdObsPrestadorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdObsPrestadorKeyReleased

    private void tfdNotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdNotaKeyReleased
        int nota = Integer.parseInt(tfdNota.getText());
        if (nota > 10) {
            JOptionPane.showMessageDialog(this, "A nota do serviço não pode ser maior que 10!");
            tfdNota.requestFocus();
        }
    }//GEN-LAST:event_tfdNotaKeyReleased

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Agendas agenda = new Agendas();
        if (tfdIdAgenda.getText().length() >= 1) {
            agenda.setId(Integer.parseInt(tfdIdAgenda.getText()));
        }
        agenda.setDescricao(tfdDescricao.getText());
        // FABRICANDO O DATE INICIO
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dt_ini = dateFormat.format(JxDataIni.getDate()).toString();
        String h_ini = tfdHoraIni.getText();
        String inicio_estimado = dt_ini + " " + h_ini;
        System.out.println("String completa: " + inicio_estimado);
        int ano = Integer.parseInt(inicio_estimado.substring(0, 4));
        int mes = Integer.parseInt(inicio_estimado.substring(5, 7));
        int dia = Integer.parseInt(inicio_estimado.substring(8, 10));
        int hora = Integer.parseInt(inicio_estimado.substring(11, 13));
        int min = Integer.parseInt(inicio_estimado.substring(14, 16));
        Date d = new Date(ano, mes, dia, hora, min, 0);
        agenda.setInicioEstimado(d);
        // FABRICANDO O DATE FIM
        String dt_fim = dateFormat.format(JxDataFim.getDate());
        String h_fim = tfdHoraFim.getText();
        String fim_estimado = dt_fim + " " + h_fim;
        System.out.println("String completa: " + fim_estimado);
        int anoF = Integer.parseInt(fim_estimado.substring(0, 4));
        int mesF = Integer.parseInt(fim_estimado.substring(5, 7));
        int diaF = Integer.parseInt(fim_estimado.substring(8, 10));
        int horaF = Integer.parseInt(fim_estimado.substring(11, 13));
        int minF = Integer.parseInt(fim_estimado.substring(14, 16));
        Date dF = new Date(anoF, mesF, diaF, horaF, minF, 0);
        agenda.setFimEstimado(dF);

        agenda.setRefClientes((Clientes) new ClientesDAO().consultarId(Integer.parseInt(tfdIdCliente.getText())));
        agenda.setRefServicosHasPrestadores((ServicosHasPrestadores) new ServicosHasPrestadoresDAO().consultarId(Integer.parseInt(tfdIdPS.getText())));
        char situacao;
        if (rdbProgramado.isSelected()) {
            situacao = 'p';
        } else if (rdbRealizado.isSelected()) {
            situacao = 'r';
        } else {
            situacao = 's';
        }
        agenda.setSituacao(situacao);
        agenda.setTempoRealizado(BigInteger.valueOf(Long.parseLong(tfdTempo.getText())));
        agenda.setValor(BigInteger.valueOf(Long.parseLong(tfdValor.getText())));
        agenda.setObsCliente(tfdObsCliente.getText());
        agenda.setObsPrestador(tfdObsPrestador.getText());
        agenda.setNota(Integer.parseInt(tfdNota.getText()));

        if (agendasDAO.registroUnico(agenda)) {
            if (tfdIdAgenda.getText().trim().isEmpty()) { //SALVAR
                if (agendasDAO.salvar(agenda)) {
                    JOptionPane.showMessageDialog(this, "Agenda criada com Sucesso!");
                    btnSalvar.setEnabled(false);
                    LimparCamposCadastro();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar nova Agenda!");
                }

            } else {  // ATUALIZAR
                agenda.setId(Integer.parseInt(tfdIdAgenda.getText()));
                if (agendasDAO.atualizar(agenda)) {
                    JOptionPane.showMessageDialog(this, "Agenda atualizada com Sucesso!");
                    btnSalvar.setEnabled(false);
                    LimparCamposCadastro();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar Agenda!\n");
                }
            }
            agendasDAO.popularTabela(tblAgendas, tfdConsultaDesc.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Serviço já cadastrado para este período!");
            tfdDescricao.requestFocus();
            tfdDescricao.setText(null);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void JxDataIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JxDataIniActionPerformed

    }//GEN-LAST:event_JxDataIniActionPerformed

    private void enviarAlerta(int id) {
        FrmPrincipal.servidor.definirMensagem(String.valueOf(id));
        FrmPrincipal.servidor.definirEnvio(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviarAlerta(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        DlgSelecionarCliente dlgSelecCliente = new DlgSelecionarCliente(null, true, this);
        dlgSelecCliente.setLocationRelativeTo(null);
        dlgSelecCliente.setModal(true);
        dlgSelecCliente.setVisible(true);
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarPrestServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestServActionPerformed
        DlgSelecionarServicoPrestador dlgSelecionarServicoPrestador = new DlgSelecionarServicoPrestador(null, true, this);
        dlgSelecionarServicoPrestador.setLocationRelativeTo(null);
        dlgSelecionarServicoPrestador.setModal(true);
        dlgSelecionarServicoPrestador.setVisible(true);
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarPrestServActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tfdValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdValorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdValorKeyReleased

    private void tfdTempoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdTempoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdTempoKeyReleased

    private void tfdHoraFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdHoraFimFocusGained
        if (JxDataFim.getDate().before(JxDataIni.getDate())) {
            JOptionPane.showMessageDialog(this, "Data de Fim deve ser maior que a data de Início!");
            JxDataFim.setDate(null);
        }
    }//GEN-LAST:event_tfdHoraFimFocusGained

    private void LimparCamposCadastro() {
        limpaCampos.limparCampos(jPanelInclusao);
        tfdDescricao.requestFocus();
    }

    private void LimparCamposConsulta() {
        limpaCampos.limparCampos(jPanelConsulta);
        tfdConsultaDataSaidaDe.setDate(null);
        tfdConsultaDataSaidaAte.setDate(null);
        tfdConsultaDesc.requestFocus();
    }

    public void pegaValorCliente(Object c) {
        Clientes cli = (Clientes) c;
        System.out.println("id: " + cli.getId());
        System.out.println("nome: " + cli.getNome());
        idCli = cli.getId();
        tfdIdCliente.setText(String.valueOf(cli.getId()));
        tfdCliente.setText(cli.getNome());
    }

    public void pegaValorServicosHasPrestadores(Object c) {
        ServicosHasPrestadores sp = (ServicosHasPrestadores) c;
        System.out.println("id: " + sp.getId());
        System.out.println("serviço: " + sp.getRefServicos().getDescricao());
        System.out.println("Prestador: " + sp.getRefPrestadores().getNome());
        idSerPres = sp.getId();
        tfdIdPS.setText(String.valueOf(sp.getId()));
        tfdPrestador.setText(String.valueOf(sp.getRefPrestadores().getNome()));
        tfdServico.setText(String.valueOf(sp.getRefServicos().getDescricao()));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker JxDataFim;
    private org.jdesktop.swingx.JXDatePicker JxDataIni;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarPrestServ;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelInclusao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdbProgramado;
    private javax.swing.JRadioButton rdbRealizado;
    private javax.swing.JRadioButton rdbSuspenso;
    private javax.swing.JTable tblAgendas;
    private javax.swing.JTextField tfdCliente;
    private javax.swing.JTextField tfdConsultaCli;
    private org.jdesktop.swingx.JXDatePicker tfdConsultaDataSaidaAte;
    private org.jdesktop.swingx.JXDatePicker tfdConsultaDataSaidaAte1;
    private org.jdesktop.swingx.JXDatePicker tfdConsultaDataSaidaDe;
    private org.jdesktop.swingx.JXDatePicker tfdConsultaDataSaidaDe1;
    private javax.swing.JTextField tfdConsultaDesc;
    private javax.swing.JTextField tfdConsultaPrest;
    private javax.swing.JTextField tfdConsultaServ;
    private javax.swing.JTextField tfdConsultaServ1;
    private javax.swing.JTextField tfdDescricao;
    private javax.swing.JFormattedTextField tfdHoraFim;
    private javax.swing.JFormattedTextField tfdHoraIni;
    private javax.swing.JTextField tfdIdAgenda;
    private javax.swing.JTextField tfdIdCliente;
    private javax.swing.JTextField tfdIdPS;
    private javax.swing.JTextField tfdNota;
    private javax.swing.JTextField tfdObsCliente;
    private javax.swing.JTextField tfdObsPrestador;
    private javax.swing.JTextField tfdPrestador;
    private javax.swing.JTextField tfdServico;
    private javax.swing.JTextField tfdTempo;
    private javax.swing.JTextField tfdValor;
    // End of variables declaration//GEN-END:variables
}
