/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Apoio.Email;
import static Apoio.Formatacao.removerFormatacao;
import Apoio.LimiteDigitos;
import static Apoio.Validacao.validarCPF;
import Apoio.limpaCampos;
import config.HibernateUtil;
import daos.ClientesDAO;
import daos.PrestadoresDAO;
import daos.SelecionarCidadesDAO;
import daos.ServicosDAO;
import daos.ServicosHasPrestadoresDAO;
import entidades.Cidades;
import entidades.Clientes;
import entidades.LogErros;
import entidades.Prestadores;
import entidades.Servicos;
import entidades.ServicosHasPrestadores;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import org.apache.commons.mail.EmailException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author adriano
 */
public class IfrPrestadores extends javax.swing.JInternalFrame {

    PrestadoresDAO prestadoresDAO;
    ServicosDAO servicosDAO;
    ServicosHasPrestadoresDAO servicosHasPrestadoresDAO;
    SelecionarCidadesDAO scDAO;
    Prestadores prestador;
    char operacao = 'i';
    int idCid = 0;
    int idSer = 0;

    /**
     * Creates new form IfrPrestadores
     */
    public IfrPrestadores() {
        initComponents();
        prestadoresDAO = new PrestadoresDAO();
        servicosDAO = new ServicosDAO();
        servicosHasPrestadoresDAO = new ServicosHasPrestadoresDAO();
        scDAO = new SelecionarCidadesDAO();
        jTabbedPane1.removeAll();
        jTabbedPane1.addTab("Consulta", pnlConsulta);
        jTabbedPane1.addTab("Cadastro", pnlCadastro);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(false);
        tfdIdCidade.setVisible(false);
        tfdNome.setDocument(new LimiteDigitos(60));
        tfdRG.setDocument(new LimiteDigitos(10));
        tfdEndereco.setDocument(new LimiteDigitos(60));
        tfdEmail.setDocument(new LimiteDigitos(45));
        prestadoresDAO.popularTabela(tblPrestadores, tfdConsulta.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelCNPJ = new javax.swing.JLabel();
        tfdSiglaEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdCidade = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        tfdIdCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfdCEP = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfdTelefone = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfdCelular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        tfdEmail = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        tfdCPF = new javax.swing.JFormattedTextField();
        tfdRG = new javax.swing.JTextField();
        pnlConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestadores = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tfdConsulta = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        pnlServicos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServicosSelecionados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfdBuscaServ = new javax.swing.JTextField();
        btnBuscaServ = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServicos1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfdValorHora = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setTitle("Cadastro de Prestadores");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("Id");

        tfdId.setEditable(false);
        tfdId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Nome");

        tfdNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdNomeKeyReleased(evt);
            }
        });

        jLabel4.setText("Estado");

        labelCNPJ.setForeground(new java.awt.Color(255, 0, 0));
        labelCNPJ.setText("CPF");

        tfdSiglaEstado.setEditable(false);
        tfdSiglaEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Cidade");

        tfdCidade.setEditable(false);
        tfdCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdCidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdCidadeKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/fin2.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tfdIdCidade.setEditable(false);
        tfdIdCidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("Endereço");

        jLabel10.setText("CEP");

        try {
            tfdCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdCEP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdCEP.setToolTipText("");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Campos em vermelho Obrigatórios");

        jLabel8.setText("Telefone");

        try {
            tfdTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdTelefone.setToolTipText("");

        jLabel9.setText("Celular");

        try {
            tfdCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdCelular.setToolTipText("");

        jLabel13.setText("E-mail");

        labelCPF.setText("RG");

        try {
            tfdCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdCPFFocusLost(evt);
            }
        });
        tfdCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdCPFKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfdIdCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdSiglaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdNome)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfdCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(labelCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdRG, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdEmail)))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18))
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCNPJ)
                    .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCPF)
                    .addComponent(tfdRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tfdCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfdCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdSiglaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(tfdIdCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(tfdCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jTabbedPane1.addTab("Cadastro", pnlCadastro);

        tblPrestadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestadoresMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPrestadoresMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestadores);

        jLabel3.setText("Nome");

        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/fin2.png"))); // NOI18N
        btnProcurar.setText("Buscar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurar)))
                .addContainerGap())
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", pnlConsulta);

        tblServicosSelecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblServicosSelecionados);

        jLabel5.setText("Busca:");

        tfdBuscaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBuscaServActionPerformed(evt);
            }
        });

        btnBuscaServ.setText("Buscar");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/fin2.png"))); // NOI18N
        btnAdicionar.setText("<< Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/delete.png"))); // NOI18N
        btnRemover.setText("Remover >>");

        tblServicos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblServicos1);

        jLabel11.setText("Serviços do Prestador:");

        jLabel14.setText("Valor Hora:");

        tfdValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdValorHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServicosLayout = new javax.swing.GroupLayout(pnlServicos);
        pnlServicos.setLayout(pnlServicosLayout);
        pnlServicosLayout.setHorizontalGroup(
            pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdBuscaServ, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscaServ))
                    .addGroup(pnlServicosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar)
                        .addGap(42, 42, 42)
                        .addComponent(btnRemover))
                    .addGroup(pnlServicosLayout.createSequentialGroup()
                        .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlServicosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlServicosLayout.setVerticalGroup(
            pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdBuscaServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaServ))
                .addGap(130, 130, 130)
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfdValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlServicosLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Serviços", pnlServicos);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/delete2.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/Save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas.apoio/exit.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addGap(14, 14, 14)
                        .addComponent(btnFechar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    //BUSCAR DADOS DO FILTRO
    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        prestadoresDAO.popularTabela(tblPrestadores, tfdConsulta.getText());
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void tblPrestadoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestadoresMouseReleased
        btnExcluir.setEnabled(true);
        btnEditar.setEnabled(true);
    }//GEN-LAST:event_tblPrestadoresMouseReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DlgSelecionarCidade dlgSelecCidade = new DlgSelecionarCidade(null, true, this);
        dlgSelecCidade.setLocationRelativeTo(null);
        dlgSelecCidade.setModal(true);
        dlgSelecCidade.setVisible(true);
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private boolean camposObrigatorios() {
        if (tfdNome.getText().length() > 0 && removerFormatacao(tfdCPF.getText()).trim().length() == 11 && tfdIdCidade.getText().length() > 0) {
            return true;
        } else {
            return false;
        }
    }

    public void pegaValor(Object c) {
        Cidades cid = (Cidades) c;
        System.out.println("id: " + cid.getId());
        System.out.println("nome: " + cid.getCidade());
        idCid = cid.getId();
        tfdIdCidade.setText(String.valueOf(cid.getId()));
        tfdCidade.setText(cid.getCidade());
        tfdSiglaEstado.setText(cid.getEstado());
    }

    public void pegaValorServico(Object s) {
//        Servicos ser = (Servicos) s;
//        System.out.println("id: " + ser.getId());
//        System.out.println("nome: " + ser.getDescricao());
//        idSer = ser.getId();
//        tfdIdServico.setText(String.valueOf(ser.getId()));
//        tfdServico.setText(ser.getDescricao());
    }

    private void tfdCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCidadeKeyReleased

    }//GEN-LAST:event_tfdCidadeKeyReleased

// Verificar Metodo com Fabricio
    private void tfdCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCidadeKeyTyped

    }//GEN-LAST:event_tfdCidadeKeyTyped

    private void tfdNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdNomeKeyReleased
        if (camposObrigatorios() == true) {
            btnSalvar.setEnabled(true);
        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_tfdNomeKeyReleased

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        prestadoresDAO.popularTabela(tblPrestadores, tfdConsulta.getText());
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblPrestadores.getSelectedRow() > -1) {
            int id = Integer.parseInt(String.valueOf(tblPrestadores.getValueAt(tblPrestadores.getSelectedRow(), 0)));
            int resposta = JOptionPane.showConfirmDialog(null, "Realmente excluir Prestador?", title, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                Prestadores p = (Prestadores) prestadoresDAO.consultarId(id);
                p.setDelete('d');
                if (prestadoresDAO.atualizar(p)) {
                    prestadoresDAO.popularTabela(tblPrestadores, tfdConsulta.getText());
                    JOptionPane.showMessageDialog(this, "Registro excluído com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir registro!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um registro!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    public void editar() {
        if (tblPrestadores.getSelectedRow() > -1) {
            int id = Integer.parseInt(String.valueOf(tblPrestadores.getValueAt(tblPrestadores.getSelectedRow(), 0)));
            Prestadores pres = (Prestadores) prestadoresDAO.consultarId(id);

            tfdId.setText(String.valueOf(pres.getId()));
            tfdNome.setText(pres.getNome());
            tfdCPF.setText(pres.getCpf());
            tfdRG.setText(pres.getRg());
            tfdTelefone.setText(pres.getTelefone());
            tfdCelular.setText(pres.getCelular());
            tfdEmail.setText(pres.getEmail());
            tfdEndereco.setText(pres.getEndereco());
            tfdCEP.setText(pres.getCep());
            tfdIdCidade.setText(String.valueOf(pres.getRefCidades().getId()));
            Cidades cid = (Cidades) scDAO.consultarId(Integer.parseInt(tfdIdCidade.getText()));
            idCid = cid.getId();
            tfdCidade.setText(cid.getCidade());
            tfdSiglaEstado.setText(cid.getEstado());
            tblPrestadores.clearSelection();
            jTabbedPane1.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um registro!");
        }
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Prestadores p = new Prestadores();
        if (tfdId.getText().length() >= 1) {
            p.setId(Integer.parseInt(tfdId.getText()));
        }
        p.setNome(tfdNome.getText());
        p.setCpf(tfdCPF.getText());
        p.setRg(tfdRG.getText());
        p.setTelefone(tfdTelefone.getText());
        p.setCelular(tfdCelular.getText());
        p.setEmail(tfdEmail.getText());
        p.setEndereco(tfdEndereco.getText());
        p.setCep(tfdCEP.getText());
        p.setRefCidades((Cidades) new SelecionarCidadesDAO().consultarId(idCid));

        if (prestadoresDAO.registroUnico(p)) {
            if (tfdId.getText().trim().isEmpty()) { //SALVAR
                if (prestadoresDAO.salvar(p)) {
                    JOptionPane.showMessageDialog(this, "Prestador salvo com Sucesso! Adicione seus serviços.");
                    prestador = p;
                    atualizaAbas(p);
                    btnSalvar.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar novo Prestador!\n");
                }

            } else {  // ATUALIZAR
                prestador.setId(Integer.parseInt(tfdId.getText()));
                if (prestadoresDAO.atualizar(prestador)) {
                    JOptionPane.showMessageDialog(this, "Prestador atualizado com Sucesso!");
                    btnSalvar.setEnabled(false);
                    LimparCamposCadastro();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar Prestador!\n");
                }
            }
            prestadoresDAO.popularTabela(tblPrestadores, tfdConsulta.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Prestador já cadastrado com este CPF!");
            tfdCPF.requestFocus();
            tfdCPF.setText(null);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfdCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdCPFFocusLost
        if (removerFormatacao(tfdCPF.getText()).trim().length() == 11) {
            if (validarCPF(removerFormatacao(tfdCPF.getText())) == true) {
                if (camposObrigatorios() == true) {
                    btnSalvar.setEnabled(true);
                } else {
                    btnSalvar.setEnabled(false);
                }
            } else {
                tfdCPF.setText("");
                JOptionPane.showMessageDialog(this, "CPF Inválido!");
                tfdCPF.requestFocus();
            }
        }
        if (removerFormatacao(tfdCPF.getText()).trim().length() == 0) {
            btnSalvar.setEnabled(false);
        }
        if (removerFormatacao(tfdCPF.getText()).trim().length() != 11 && removerFormatacao(tfdCPF.getText()).trim().length() != 0) {
            JOptionPane.showMessageDialog(this, "CPF Inválido!");
            tfdCPF.setText("");
            tfdCPF.requestFocus();
        }

    }//GEN-LAST:event_tfdCPFFocusLost

    private void tfdCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCPFKeyReleased
        if (removerFormatacao(tfdCPF.getText()).trim().length() == 11) {
            if (validarCPF(removerFormatacao(tfdCPF.getText())) == true) {
                btnSalvar.setEnabled(true);
            } else {
                btnSalvar.setEnabled(false);
            }

        } else {
            btnSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_tfdCPFKeyReleased

    private void tblPrestadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestadoresMouseClicked
        if (evt.getClickCount() >= 2) {
            editar();
        }
    }//GEN-LAST:event_tblPrestadoresMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (tblServicos1.getSelectedRow() > -1 && ! tfdValorHora.getText().isEmpty()) {
            ServicosHasPrestadores sp = new ServicosHasPrestadores();
            sp.setRefPrestadores(prestador);
            sp.setRefServicos((Servicos) servicosDAO.consultarId(Integer.parseInt(String.valueOf(tblServicos1.getValueAt(tblServicos1.getSelectedRow(), 0)))));
            //sp.setValorHora(tfdValorHora.getText());
//            if (servicosHasPrestadoresDAO.salvar(sp) == false) {
//                JOptionPane.showMessageDialog(this, "Atleta já adicionado à equipe.");
//            }
//            competicaoDAO.popularTabelaEquipe(tblEquipe, competicao);
        } else {
            JOptionPane.showMessageDialog(this, "Necessário selecionar um Serviço e preencher o Valor Hora!");
        }
//        DlgSelecionarServico dlgSelecServico = new DlgSelecionarServico(null, true, this);
//        dlgSelecServico.setLocationRelativeTo(null);
//        dlgSelecServico.setModal(true);
//        dlgSelecServico.setVisible(true);
//        if (camposObrigatorios() == true) {
//            btnSalvar.setEnabled(true);
//        } else {
//            btnSalvar.setEnabled(false);
//        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tfdBuscaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdBuscaServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdBuscaServActionPerformed

    private void tfdValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdValorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdValorHoraActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        LimparCamposCadastro();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void LimparCamposCadastro() {
        prestador = null;
        limpaCampos.limparCampos(pnlCadastro);
        jTabbedPane1.remove(pnlServicos);
        tfdNome.requestFocus();
    }

    private void atualizaAbas(Prestadores p) {
        jTabbedPane1.add("Serviços", pnlServicos);
        servicosDAO.popularTabela(tblServicos1, tfdBuscaServ.getText());
        servicosHasPrestadoresDAO.popularTabelaPorPrestador(tblServicosSelecionados, p.getId());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscaServ;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCNPJ;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JPanel pnlServicos;
    private javax.swing.JTable tblPrestadores;
    private javax.swing.JTable tblServicos1;
    private javax.swing.JTable tblServicosSelecionados;
    private javax.swing.JTextField tfdBuscaServ;
    private javax.swing.JFormattedTextField tfdCEP;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JFormattedTextField tfdCelular;
    private javax.swing.JTextField tfdCidade;
    private javax.swing.JTextField tfdConsulta;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdEndereco;
    private javax.swing.JTextField tfdId;
    private javax.swing.JTextField tfdIdCidade;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdRG;
    private javax.swing.JTextField tfdSiglaEstado;
    private javax.swing.JFormattedTextField tfdTelefone;
    private javax.swing.JTextField tfdValorHora;
    // End of variables declaration//GEN-END:variables
}
